### PR TITLE
Don’t allow people to put more than 5 grants on a dream

### PR DESCRIPTION
**Pull request by flov**

### CODE REVIEW

**Comment by hesslau** [comment]
Hey Flo,

Some points to consider:
* The number of grants in question isn't actually 5, but 50% of grants available (see ENV['DEFAULT_HEARTS']
* you can get the amount of all grants spent by a user by calling Grant.find_by(user..).pluck(: amount).sum() - no need to create a new field for this

**Comment by flov** [comment]
Regarding the two points:
- thanks, I was searching for that `ENV['DEFAULT_HEARTS']` I will make the changes accordingly
- it has been implemented just like that:
`    user_grants_for_camp = Grant.where(camp_id: @camp.id, user_id: current_user.id).
                                    pluck(:amount).sum`
what do you mean with no need to create a new field?

**Comment by flov** [comment]
btw, you can also comment on a line in the code. It helps to understand better which part of the code you are commenting on

**Comment by hesslau** [comment]
Oops, sorry. I thought you're creating a new field with

> has_many :created_grants, class_name: :Grant

It's late. I should go to sleep.

Ok, I'll accept the PR once the limit isn't hardcoded anymore

**Comment by flov** [comment]
I've added the changes just as you commented :)
I've added this line so that I can easily see the grants for a user in the console.
It's not really needed for the functionality of this feature but I think it's nice to have that relation in the model when there is a belongs_to :user relation coming from `Grant`

**Pull request merged**
